player-inventory:
  pet-slots: [ 9, 10, 11, 12, 13 ]
  pet-item:
    name: "<white><bold>{name}</bold></white> <yellow>(Equipped)</yellow>" # {name}
    # {description} adds description lines in between other contents of line
    lore:
      - "<gray>{description}</gray>"
      - ""
      - "<green><bold>Click</bold></green> <gray>to unequip</gray>"
  empty-slot-item:
    material: BLACK_STAINED_GLASS_PANE
    name: "<white>Empty Slot</white>"
  locked-slot-item:
    material: RED_STAINED_GLASS_PANE
    name: "<white>Locked Slot</white>"

pets-menu:
  pet-item:
    equipped:
      name: "<white><bold>{name}</bold></white> <yellow>(Equipped)</yellow>" # {name}
      # {description} adds description lines in between other contents of line
      # {equip_info} add line depending on whether pet is equipped
      lore:
        - "<gray>{description}</gray>"
        - ""
        - "<green><bold>Click</bold></green> <gray>to unequip</gray>"
    unequipped:
      name: "<white><bold>{name}</bold></white>" # {name}
      # {description} adds description lines in between other contents of line
      # {equip_info} add line depending on whether pet is equipped
      lore:
        - "<gray>{description}</gray>"
        - ""
        - "<green><bold>Click</bold></green> <gray>to equip</gray>"