name: DynamicPets
version: '1.0-SNAPSHOT'
main: me.cable.dynamicpets.DynamicPets
api-version: '1.21'

commands:
  dynamicpets:
    permission: "dynamicpets.command.dynamicpets"
    aliases:
      - "dp"